apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 1h
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: 2.17.x
      sourceRef:
        kind: HelmRepository
        name: kedacore
  valuesFrom:
    - kind: ConfigMap
      name: keda-values 