apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent-httproute
spec:
  parentRefs:
  - name: mdch-lab
    namespace: cilium
  hostnames:
  - "qbittorrent.mdch-lab.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
  - backendRefs:
    - name: qbittorrent-web
      port: 80