apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartshopper
resources:
  - frontend-blue-green.yaml
  - frontend-deployment.yaml
  - frontend-hpa.yaml
  - frontend-image.yaml