
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: 2.3.x
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values