affinity:
  nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1

persistence:
  media:
    enabled: false

volumeMounts:
  - name: jellyfin-media
    mountPath: /nfs-jellyfin
    readOnly: false

volumes:
  - name: jellyfin-media
    nfs:
      server: 192.168.1.98
      path: /nfs/Plex
      readOnly: false