affinity:
  nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1

VolumeMounts:
  - name: jellyfin-media
    mountPath: /nfs-jellyfin
    readOnly: false

Volumes:
  - name: jellyfin-media
    nfs:
      server: 192.168.1.98
      path: /nfs/plex
      readOnly: false