apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monkeytype-frontend-httproute
  namespace: monkeytype
spec:
  parentRefs:
    - name: mdch-lab-gateway
      namespace: cilium
  hostnames:
    - "monkeytype.mdch-lab.dev"
  backendRefs:
    - name: frontend-service
      port: 80

