apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monkeytype
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: monkeytype/monkeytype-frontend:25.22.0
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-url
        - secretRef:
            name: firebase-env
        env:
        - name: RECAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: google-recaptcha
              key: RECAPTCHA_SITE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: monkeytype
spec:
  selector:
    app: frontend
  ports:
  - port: 80
