apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onlineboutique
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
  - httproute.yaml
configMapGenerator:
  - name: onlineboutique-values
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: onlineboutique
configurations:
  - kustomizeconfig.yaml