
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlineboutique
spec:
  interval: 1h
  releaseName: onlineboutique
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: onlineboutique
      sourceRef:
        kind: HelmRepository
        name: onlineboutique
  valuesFrom:
    - kind: ConfigMap
      name: onlineboutique-values