apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flagger
spec:
  interval: 24h
  url: oci://ghcr.io/fluxcd/charts/flagger
  ref:
    semver: 1.41.0
  verify:
    provider: cosign
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flagger-loadtester
spec:
  interval: 24h
  url: https://flagger.app
