apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "v2.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
    - source-watcher
  cluster:
    size: small
  sync:
    kind: GitRepository
    url: https://github.com/noambenm/mdch-lab.git
    ref: "refs/heads/main"
    path: clusters/production
    pullSecret: flux-system
  kustomize:
    patches:
      # 1. Source Controller
      - target:
          kind: Deployment
          name: source-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: gcp-token
              projected:
                sources:
                - serviceAccountToken:
                    audience: https://iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/fluxcd
                    expirationSeconds: 3600
                    path: gcp-token
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: workload-identity-credential-configuration
              configMap:
                name: source-controller-workload-identity-federation
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: gcp-token
              mountPath: /var/run/service-account
              readOnly: true
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: workload-identity-credential-configuration
              mountPath: /etc/workload-identity
              readOnly: true

      # 2. Kustomize Controller
      - target:
          kind: Deployment
          name: kustomize-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: gcp-token
              projected:
                sources:
                - serviceAccountToken:
                    audience: https://iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/fluxcd
                    expirationSeconds: 3600
                    path: gcp-token
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: workload-identity-credential-configuration
              configMap:
                name: kustomize-controller-workload-identity-federation
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: gcp-token
              mountPath: /var/run/service-account
              readOnly: true
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: workload-identity-credential-configuration
              mountPath: /etc/workload-identity
              readOnly: true

      # 3. Helm Controller
      - target:
          kind: Deployment
          name: helm-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: gcp-token
              projected:
                sources:
                - serviceAccountToken:
                    audience: https://iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/fluxcd
                    expirationSeconds: 3600
                    path: gcp-token
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: workload-identity-credential-configuration
              configMap:
                name: helm-controller-workload-identity-federation
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: gcp-token
              mountPath: /var/run/service-account
              readOnly: true
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: workload-identity-credential-configuration
              mountPath: /etc/workload-identity
              readOnly: true

      # 4. Notification Controller
      - target:
          kind: Deployment
          name: notification-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: gcp-token
              projected:
                sources:
                - serviceAccountToken:
                    audience: https://iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/fluxcd
                    expirationSeconds: 3600
                    path: gcp-token
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: workload-identity-credential-configuration
              configMap:
                name: notification-controller-workload-identity-federation
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: gcp-token
              mountPath: /var/run/service-account
              readOnly: true
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: workload-identity-credential-configuration
              mountPath: /etc/workload-identity
              readOnly: true

      # 5. Image Reflector Controller
      - target:
          kind: Deployment
          name: image-reflector-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: gcp-token
              projected:
                sources:
                - serviceAccountToken:
                    audience: https://iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/fluxcd
                    expirationSeconds: 3600
                    path: gcp-token
          - op: add
            path: /spec/template/spec/volumes/-
            value:
              name: workload-identity-credential-configuration
              configMap:
                name: image-reflector-controller-workload-identity-federation
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: gcp-token
              mountPath: /var/run/service-account
              readOnly: true
          - op: add
            path: /spec/template/spec/containers/0/volumeMounts/-
            value:
              name: workload-identity-credential-configuration
              mountPath: /etc/workload-identity
              readOnly: true
