---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 3m
  retryInterval: 2m
  prune: true
  force: true
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./controllers
  patches:
    - patch: |
        - op: add
          path: /spec/values
          value:
            k8sClientRateLimit:
              qps: 50
              burst: 200
            k8sServiceHost: "192.168.1.10"
            k8sServicePort: 6443
            l2announcements:
              enabled: true
            ingressController:
              enabled: true
              default: true
              loadbalancerMode: shared
              service:
                loadBalancerIP: "192.168.1.30"
                allocateLoadBalancerNodePorts: false
            ipam:
              operator:
                clusterPoolIPv4PodCIDRList:
                  - "10.42.0.0/16"
            kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
            operator:
              replicas: 1
      target:
        kind: HelmRelease
        name: cilium
        namespace: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  prune: true
