---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/values
          value:
            k8sServiceHost: "192.168.1.10"
            k8sServicePort: 6443
            l2announcements:
              enabled: true
            ingressController:
              enabled: true
              default: true
              loadbalancerMode: shared
              service:
                loadBalancerIP: "192.168.1.30"
                allocateLoadBalancerNodePorts: false
            ipam:
              operator:
                clusterPoolIPv4PodCIDRList:
                  - "10.42.0.0/16"
            kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
            operator:
              replicas: 1
      target:
        kind: HelmRelease
        name: cilium
        namespace: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
        namespace: cert-manager
    - patch: |
        - op: replace
          path: /spec/commonName
          value: "*.mdch-lab.dev"
        - op: replace
          path: /spec/dnsNames/0
          value: "*.mdch-lab.dev"
        - op: replace
          path: /spec/dnsNames/1
          value: mdch-lab.dev
      target:
        kind: Certificate
        name: wildcard-cert
        namespace: cilium
