apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcpsm
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: TOKEN
    remoteRef:
      key: cloudflare-tunnel-token
