apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 25days-secrets
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: 25days-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: /25days/aws/access-key
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: /25days/aws/secret-access-key
  - secretKey: AWS_REGION
    remoteRef:
      key: /25days/aws/region
  - secretKey: AWS_BUCKET_NAME
    remoteRef:
      key: /25days/aws/bucket-name
  - secretKey: DATABASE_URL
    remoteRef:
      key: 	/25days/database-url
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: /25days/db/name