apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-sa-key
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: ClusterSecretStore
  target:
    name: firebase-sa-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: firebase-service-account.json
    remoteRef:
      key: /smartshopper/firebase/service-account-json