apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-auth0-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: frontend-auth0-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:

  - secretKey: REACT_APP_FIREBASE_API_KEY
    remoteRef:
      key: /smartshopper/firebase/api-key

  - secretKey: REACT_APP_FIREBASE_AUTH_DOMAIN
    remoteRef:
      key: /smartshopper/firebase/auth-domain

  - secretKey: REACT_APP_FIREBASE_PROJECT_ID
    remoteRef:
      key: /smartshopper/firebase/project-id

  - secretKey: REACT_APP_FIREBASE_STORAGE_BUCKET
    remoteRef:
      key: /smartshopper/firebase/storage-bucket

  - secretKey: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
    remoteRef:
      key: /smartshopper/firebase/messaging-sender-id

  - secretKey: REACT_APP_FIREBASE_APP_ID
    remoteRef:
      key: /smartshopper/firebase/app-id