
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
spec:
  interval: 1h
  releaseName: dashy
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: dashy
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: selfhosted-helmcharts
  values:
    static:
      existingSecret: dashy-conf