apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backend-blue-green
  namespace: smartshopper
spec:
  provider: gatewayapi:v1
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: backend-hpa
  service:
    name: backend-service
    port: 80
    targetPort: 8000
    hosts:
     - smartshopper-app.mdch-lab.dev
    gatewayRefs:
      - name: mdch-lab-gateway
        namespace: cilium
    match:
      - uri:
          prefix: /api
  analysis:
    interval: 40s
    threshold: 1
    iterations: 3
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -host smartshopper-app.mdch-lab.dev/api https://cilium-gateway-mdch-lab-gateway.cilium/"