---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infrastructure
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/infrastructure/**"
          to: "@artifact/"
          exclude:
            - "infrastructure/controllers/cilium/**"
            - "controllers/cilium/**"
            - "**/cilium/**"
            - "infrastructure/configs/cilium/**"
            - "configs/cilium/**"
            - "infrastructure/controllers/descheduler/**"
            - "controllers/descheduler/**"
            - "**/descheduler/**"
            - "infrastructure/controllers/longhorn/**"
            - "controllers/longhorn/**"
            - "**/longhorn/**"
            - "infrastructure/controllers/gateway-api/**"
            - "controllers/gateway-api/**"
            - "**/gateway-api/**"
            - "infrastructure/controllers/crossplane/**"
            - "controllers/crossplane/**"
            - "**/crossplane/**"
            - "infrastructure/configs/crossplane/**"
            - "configs/crossplane/**"
            - "infrastructure/configs/coredns-custom.yaml"
            - "configs/coredns-custom.yaml"
            - "**/coredns-custom.yaml"
            - "infrastructure/configs/grafana/**"
            - "configs/grafana/**"
            - "**/configs/grafana/**"
    - name: apps
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/apps/base/**"
          to: "@artifact/base/"
        - from: "@monorepo/apps/staging/**"
          to: "@artifact/staging/"
