---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 3m
  retryInterval: 2m
  prune: true
  force: true
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./controllers
  patches:
    - patch: |
        - op: replace
          path: /spec/ref
          value: 
            semver: 1.x
      target:
        kind: OCIRepository
        name: cert-manager
        namespace: cert-manager
    - patch: |
        - op: replace
          path: /spec/ref
          value:
            semver: 1.x
      target:
        kind: OCIRepository
        name: flagger
        namespace: flagger-system
    - patch: |
        - op: replace
          path: /spec/ref
          value:
            semver: '*'
      target:
        kind: OCIRepository
        name: kube-prometheus-stack
        namespace: monitoring
    - patch: |
        - op: replace
          path: /spec/ref
          value:
            semver: 1.x
      target:
        kind: OCIRepository
        name: cilium
        namespace: cilium
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          value: 1.x
      target:
        kind: HelmRelease
        name: external-secrets
        namespace: external-secrets
    - patch: |
        - op: add
          path: /spec/values
          value:
            gke:
              enabled: true
            ipam:
              mode: kubernetes
            cni:
              binPath: /home/kubernetes/bin
            nodeinit:
              enabled: true
              reconfigureKubelet: true
              removeCbrBridge: true
              removeNodeTaints: true
            ipv4NativeRoutingCIDR: 192.168.0.0/18
      target:
        kind: HelmRelease
        name: cilium
        namespace: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  wait: true
  timeout: 3m
  retryInterval: 2m
  prune: true
  force: true
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-staging-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
    - patch: |
        - op: replace
          path: /spec/commonName
          value: "*.staging.mdch-lab.dev"
        - op: replace
          path: /spec/dnsNames/0
          value: "*.staging.mdch-lab.dev"
        - op: replace
          path: /spec/dnsNames/1
          value: staging.mdch-lab.dev
      target:
        kind: Certificate
        name: wildcard-cert
        namespace: cilium
    - patch: |
        - op: replace
          path: /spec/provider/gcpsm/auth
          value:
            workloadIdentity:
              serviceAccountRef:
                name: gcpsm-sa
                namespace: external-secrets
      target:
        kind: ClusterSecretStore
        name: gcpsm
    - patch: |
        - op: replace
          path: /spec/auth
          value:
            workloadIdentity:
              serviceAccountRef:
                name: gcr-sa
                namespace: external-secrets
              clusterLocation: me-west1-c
              clusterName: mdch-lab-staging-cluster-olf0
      target:
        kind: GCRAccessToken
        name: gcr-gen
        namespace: external-secrets
