---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 5m
  url: oci://me-west1-docker.pkg.dev/noambesandbox/mdch-lab/pihole
  ref:
    tag: latest
  provider: gcp
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/noambenm/mdch-lab.*$"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  prune: true
  interval: 10m
  retryInterval: 1m
  path: ./
  sourceRef:
    kind: OCIRepository
    name: pihole
  targetNamespace: pihole
  wait: true
  timeout: 5m
