gatewayAPI:
  enabled: true
  gatewayClass:
    create: 'true'

kubeProxyReplacement: "true"

loadBalancer:
  l7:
    backend: envoy

hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true


prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true

dashboards:
  enabled: true

envoy:
  rollOutPods: true
  prometheus:
    serviceMonitor:
      enabled: true

rollOutCiliumPods: true
