apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcpsm
    kind: ClusterSecretStore
  target:
    name: pihole-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: pihole-password
