apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo-blue-green-gateway-api
  namespace: test
spec:
  provider: gatewayapi:v1
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # KEDA ScaledObject reference for event-driven autoscaling
  autoscalerRef:
    apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    name: podinfo-so
  service:
    # service port number
    port: 9898
    # container port number or name (optional)
    targetPort: 9898
    # Gateway API HTTPRoute host names
    hosts:
     - podinfo.mdch-lab.dev
    # Reference to the Gateway that the generated HTTPRoute would attach to.
    gatewayRefs:
      - name: mdch-lab-gateway
        namespace: cilium
  analysis:
    # schedule interval (default 60s)
    interval: 40s
    # max number of failed checks before rollback
    threshold: 1
    # number of checks to run before rollback
    iterations: 3
    # Prometheus checks based on 
    # http_request_duration_seconds histogram
    metrics:
    - name: error-rate
      templateRef:
        name: error-rate
      thresholdRange:
        max: 1
      interval: 30s
    - name: latency
      templateRef:
        name: latency
      thresholdRange:
        max: 0.5
      interval: 30s
    # testing (optional)
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.test/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -sd 'anon' http://podinfo-canary.test:9898/token | grep token"
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -host podinfo.mdch-lab.dev https://cilium-gateway-mdch-lab-gateway.cilium/"