apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "./kustomize/deployment.yaml"
  prune: true
  timeout: 1m