apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: test
spec:
  interval: 1h
  releaseName: flagger-loadtester
  chart:
    spec:
      chart: loadtester
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: flagger-loadtester
        namespace: flagger-system