
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 1h
  releaseName: podinfo
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: podinfo
      version: 6.5.4
      sourceRef:
        kind: HelmRepository
        name: podinfo
      verify:
        provider: cosign
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values