apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  type: githubdispatch
  address: https://github.com/noambenm/mdch-lab
  secretRef:
    name: flux-system
