
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 1h
  releaseName: pihole
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: pihole
      version: 2.34.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
