apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend-blue-green
  namespace: smartshopper
spec:
  provider: gatewayapi:v1
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  progressDeadlineSeconds: 60
  service:
    name: frontend-service
    port: 80
    hosts:
     - smartshopper-app.mdch-lab.dev
    gatewayRefs:
      - name: mdch-lab-gateway
        namespace: cilium
    match:
      - uri:
          prefix: /
  analysis:
    interval: 40s
    threshold: 1
    iterations: 3
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -host smartshopper-app.mdch-lab.dev https://cilium-gateway-mdch-lab-gateway.cilium/"