apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ssm-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: secret-access-key