apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 1.2.x
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values 
