apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: backend-

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: podinfo

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/targetRef/name
      value: backend-podinfo
    - op: replace
      path: /spec/autoscalerRef/name
      value: backend-podinfo-so
  target:
    group: flagger.app
    version: v1beta1
    kind: Canary
    name: podinfo-canary
- patch: |-
    - op: replace
      path: /spec/scaleTargetRef/name
      value: backend-podinfo
  target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledObject
    name: podinfo-so
- patch: |-
    - op: add
      path: /spec/selector/matchLabels/app.kubernetes.io~1component
      value: backend
  target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: podinfo
- patch: |-
    - op: add
      path: /spec/values
      value:
        redis:
          enabled: true
  target:
    group: helm.toolkit.fluxcd.io
    version: v2
    kind: HelmRelease
    name: podinfo