---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    app.kubernetes.io/component: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/cilium/charts/cilium
  ref:
    digest: sha256:e6af2ea4c95ed5e439152814927c83ccce7188d49a7815f6a1f5181804e89a20 # version 1.18.6+e6af2ea4c95e
#  verify:
#    provider: cosign
#    matchOIDCIdentity:
#      - issuer: "^https://token.actions.githubusercontent.com$"
#        subject: "^https://github.com/cilium/cilium/.*$"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  releaseName: cilium
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 1h
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
