apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: informative-website-blue-green
  namespace: smartshopper
spec:
  provider: gatewayapi:v1
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: informative-website
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: informative-website-hpa
  service:
    name: informative-website-service
    port: 80
    hosts:
     - smartshopper.mdch-lab.dev
    gatewayRefs:
      - name: mdch-lab
        namespace: cilium
  analysis:
    interval: 40s
    threshold: 1
    iterations: 3
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -host smartshopper.mdch-lab.dev https://cilium-gateway-mdch-lab.cilium/"