apiVersion: apps/v1
kind: Deployment
metadata:
  name: informative-website
  namespace: smartshopper
spec:
  selector:
    matchLabels:
      app: informative-website
  template:
    metadata:
      labels:
        app: informative-website
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - informative-website
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: ecr-creds
      containers:
      - name: informative-website
        image: 438465130856.dkr.ecr.us-east-1.amazonaws.com/smartshopper/smartshopper-informative-website:0.1.8 # {"$imagepolicy": "smartshopper:informative-website-policy"}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: frontend-url
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
