apiVersion: apps/v1
kind: Deployment
metadata:
  name: 25days
  namespace: smartshopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 25days
  template:
    metadata:
      labels:
        app: 25days
    spec:
      imagePullSecrets:
      - name: ecr-creds
      containers:
      - name: 25days
        image: 438465130856.dkr.ecr.us-east-1.amazonaws.com/smartshopper/25days:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: 25days-secrets
        env:
        - name: MYSQL_HOST
          valuesFrom:
            secretKeyRef:
              name: db-creds
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valuesFrom:
            secretKeyRef:
              name: db-creds
              key: MYSQL_PORT
        - name: MYSQL_USER
          valuesFrom:
            secretKeyRef:
              name: db-creds
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valuesFrom:
            secretKeyRef:
              name: db-creds
              key: MYSQL_PASSWORD
        - name: MYSQL_PASSWORD
          valuesFrom:
            secretKeyRef:
              name: db-creds
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: service-25days
  namespace: smartshopper
spec:
  selector:
    app: 25days
  ports:
  - port: 80
    targetPort: 3000

