apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: frontend-

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: podinfo

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/targetRef/name
      value: frontend-podinfo
    - op: replace
      path: /spec/autoscalerRef/name
      value: frontend-podinfo-so
  target:
    group: flagger.app
    version: v1beta1
    kind: Canary
    name: podinfo-canary
- patch: |-
    - op: replace
      path: /spec/scaleTargetRef/name
      value: frontend-podinfo
  target:
    group: keda.sh
    version: v1alpha1
    kind: ScaledObject
    name: podinfo-so
- patch: |-
    - op: add
      path: /spec/selector/matchLabels/app.kubernetes.io~1component
      value: frontend
  target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: podinfo
configMapGenerator:
- name: podinfo-values
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml